<?php

namespace Plugin\ErrorNotify\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ErrorNotify\Entity\ErrorLog;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ErrorLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorLogRepository extends AbstractRepository
{
    /**
     * ErrorLogRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ErrorLog::class);
    }

    /**
     * @param int $id
     *
     * @return null|ErroLog
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * @param Array $conditions
     * @return QueryBuilder $qb
     */
    public function getQueryBuilderBySearchData($conditions = []){
        $qb = $this->createQueryBuilder('el');

        return $qb;
    }
}
