# 設定で置き換え用のパラメータ
parameters:
    # メールパラメータ
    from_email: "%%from_email%%"
    to_email: "%%to_email%%"
    send_level: "%%send_level%%"
    record_level: "%%record_level%%"
    record_deduplicated_time: "%%record_deduplicated_time%%"
    send_deduplicated_time: "%%send_deduplicated_time%%"

# カスタムハンドラー
services:
    plugin.error_notify.service.error_log_service:
        class: Plugin\ErrorNotify\Service\ErrorLogService
    plugin.error_notify.monolog.handler.error_log_db_handler:
        class: Plugin\ErrorNotify\Monolog\Handler\ErrorLogDBHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@plugin.error_notify.service.error_log_service'
            - '%record_level%'

    plugin.error_notify.monolog.handler.error_log_mailer_handler:
        class: Plugin\ErrorNotify\Monolog\Handler\ErrorLogMailerHandler
        arguments:
            - '@swiftmailer.mailer.default.transport.real'
            - '@plugin.error_notify.service.error_log_service'
            - '%send_level%'
            - "%to_email%"
            - "%from_email%"


# ログ計測の設定
monolog:
    handlers:
        # fingers_crossed
        main:
            type:         fingers_crossed
            action_level: DEBUG
            channels: ['front', 'admin', 'php', 'app']
            handler:    grouped
        grouped:
            type: group
            members: %%members%%

        # ログファイルの保存
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            
        